# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='video',
            field=models.TextField(verbose_name='Ссылка на видео'),
        ),
    ]
