# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 09:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('channel', '0002_auto_20161229_1211'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together=set([('user', 'channel')]),
        ),
    ]
